name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Add GitHub to known hosts
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts

      - name: Add EC2 instance to known hosts
        run: ssh-keyscan -H 54.90.86.118 >> ~/.ssh/known_hosts

      - name: Deploy to production
        run: ssh -o StrictHostKeyChecking=no ubuntu@54.90.86.118 "
          sudo mkdir -p /var/www/app &&
          sudo chown ubuntu:ubuntu /var/www/app &&
          cd /var/www/app &&
          if [ ! -d .git ]; then git clone git@github.com:ShlomyR/DevOps-start.git .; fi &&
          git pull &&
          npm install &&
          sudo systemctl restart app"

