name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name devops1

      - name: Build and Push Docker Image
        run: |
          docker build -t devopsTest.azurecr.io/myapp:latest .
          docker push devopsTest.azurecr.io/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACI
        run: |
          az container create --resource-group shlomyGroup \
            --name my-fastapi-container \
            --image devopsTest.azurecr.io/myapp:latest \
            --cpu 1 --memory 1 \
            --registry-login-server devopsTest.azurecr.io \
            --registry-username $(az acr credential show --name devopsTest --query username --output tsv) \
            --registry-password $(az acr credential show --name devopsTest --query passwords[0].value --output tsv) \
            --dns-name-label my-fastapi-app \
            --ports 8000 \
            --os-type Linux
