name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode and set up SSH key
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/my-ssh-key.pem  # Use raw private key
          chmod 400 ~/.ssh/my-ssh-key.pem

      - name: Add EC2 instance to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-54-226-202-57.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-ssh-key.pem ubuntu@ec2-54-226-202-57.compute-1.amazonaws.com "
          sudo mkdir -p /var/www/app &&
          sudo chown ubuntu:ubuntu /var/www/app &&
          cd /var/www/app &&
          if [ ! -d .git ]; then git clone git@github.com:your-username/your-repo.git .; fi &&
          git pull &&
          npm install &&
          sudo systemctl restart app"
