name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up Docker Buildx for better caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Log in to GitHub Container Registry (GHCR) (Optional)
      - name: Log in to GHCR
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # ✅ Define image name & tags
      - name: Set image tags
        id: vars
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # ✅ Build and test Docker image
      - name: Build Docker image
        run: |
          docker build -t postgres:latest .

      # ✅ Run tests inside the container
      - name: Run tests
        run: |
          docker run --rm postgres pytest

      # ✅ Tag and push to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker tag postgres:latest ${{ secrets.DOCKER_USERNAME }}/postgres:${{ env.IMAGE_TAG }}
          docker tag postgres:latest ${{ secrets.DOCKER_USERNAME }}/postgres:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres:latest

      # ✅ Tag and push to GHCR (Optional)
      - name: Push to GHCR
        run: |
          docker tag postgres:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/postgres:${{ env.IMAGE_TAG }}
          docker tag postgres:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/postgres:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/postgres:${{ env.IMAGE_TAG }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/postgres:latest
