name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        # ✅ Checkout code
        uses: actions/checkout@v4

      # ✅ Log in to GitHub Container Registry (GHCR) (Optional)
      - name: Log in to GHCR
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
        run: git clone $GITHUB_REPOSITORY

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to production
        run: ssh ubuntu@server "cd /var/www/app && git pull && npm install && systemctl restart app"
