name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name devops1

      - name: Build and Push Docker Image
        run: |
          docker build -t devops1.azurecr.io/myapp:latest .
          docker push devops1.azurecr.io/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACI
        run: |
          az container create --resource-group shlomyGroup \
            --name my-fastapi-container \
            --image devops1.azurecr.io/myapp:latest \
            --cpu 1 --memory 1 \
            --registry-login-server devops1.azurecr.io \
            --registry-username ${{ secrets.AZURE_CLIENT_USER_NAME }} \
            --registry-password ${{ secrets.AZURE_CLIENT_PASSWORD }} \
            
            --ports 8000 \
            --os-type Linux
