name: Terraform Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: 03-Multi-Tier_Web_Application/Terraform

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"
        working-directory: 03-Multi-Tier_Web_Application/Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: 03-Multi-Tier_Web_Application/Terraform
